excluded: # paths to ignore during linting. Takes precedence over `included`.
  - LiveStreamTests

  
line_length: 150
function_body_length: 60
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - nesting
