
default_platform :ios

platform :ios do
  before_all do
     sh "pod update"
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "LiveStream.xcworkspace",
      scheme: "LiveStream",
      configuration: "Debug",
      skip_build: true,
      code_coverage: true,
      output_directory: "deploy",
      derived_data_path: "deploy/",
      output_types: "html"
    )
    coverage
  end
  # Code Coverage
  desc "Code Coverage"
  lane :coverage do
    slather
  end

  lane :appstore_testflight do
    #cert
    #sigh(force: true)
    # increment_build_number
    gym(
      scheme: "LiveStream",
      workspace: "LiveStream.xcworkspace",
      output_directory: "deploy",
      output_name: "LiveStream.ipa",
      archive_path: "deploy/",
      configuration: "Release")
    #testflight(skip_waiting_for_build_processing: true) 
  end

  after_all do |lane|
  end

end



